### Generated by Copilot


"""Tests for angle_encoding_layer with randomize_entangling=True.

Checks that:
  - el_* parameters land in [0, π] after randomization
  - el_* parameters differ from the non-randomized defaults
  - randomize_entangling does not add nn.Parameter entries to the layer
  - randomized entangling params actually affect the output quantum state
"""

import math
import sys
from pathlib import Path

import pytest
import torch

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from encodings_merlin.encoding_layers import angle_encoding_layer  # noqa: E402

NUM_FEATURES = 4


# ── helpers ────────────────────────────────────────────────────────────────


def _el_params(layer):
    """Return pcvl Parameter objects whose name starts with 'el_'.

    Uses all_params=True so that fixed (non-trainable) parameters set via
    fix_value are also returned; they no longer appear in the default
    get_parameters() call after being fixed.
    """
    return [
        p
        for p in layer.circuit.get_parameters(all_params=True)
        if p.name.startswith("el_")
    ]


def _copy_trainable_params(src, dst):
    """Copy trainable nn.Parameters from src into dst so outputs only differ
    due to circuit (el_*) parameters."""
    for p_src, p_dst in zip(src.parameters(), dst.parameters()):
        p_dst.data.copy_(p_src.data)


# ── tests ──────────────────────────────────────────────────────────────────


class TestElParamValues:
    def test_randomized_el_params_are_in_range(self):
        """Every el_* param must land in [0, π] after randomization."""
        layer = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=True
        )
        el = _el_params(layer)
        assert len(el) > 0, "No el_* params found in the pcvl circuit"
        for p in el:
            val = float(p)
            assert (
                0.0 <= val <= math.pi
            ), f"Parameter '{p.name}' = {val:.4f} is outside [0, π]"

    def test_randomized_el_params_differ_between_instances(self):
        """Two independently-created randomized layers must have different el_*
        values, confirming that each call draws fresh random samples."""
        layer_a = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=True
        )
        layer_b = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=True
        )
        vals_a = [float(p) for p in _el_params(layer_a)]
        vals_b = [float(p) for p in _el_params(layer_b)]

        assert vals_a != vals_b, (
            "Two independently randomized layers have identical el_* params "
            "— randomization is not working"
        )

    def test_input_size_0_false_el_params_in_range(self):
        """el_* params also land in [0, π] for the input_size_0=False variant."""
        layer = angle_encoding_layer(
            num_features=NUM_FEATURES, input_size_0=False, randomize_entangling=True
        )
        el = _el_params(layer)
        assert len(el) > 0
        for p in el:
            val = float(p)
            assert (
                0.0 <= val <= math.pi
            ), f"Parameter '{p.name}' = {val:.4f} is outside [0, π]"


class TestTrainableParamCount:
    def test_randomize_does_not_change_trainable_param_count(self):
        """randomize_entangling must not alter the number of nn.Parameters."""
        layer_default = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=False
        )
        layer_random = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=True
        )
        n_default = sum(p.numel() for p in layer_default.parameters())
        n_random = sum(p.numel() for p in layer_random.parameters())
        assert (
            n_default == n_random
        ), f"Default has {n_default} trainable scalars, randomized has {n_random}"

    def test_el_params_absent_from_nn_parameters(self):
        """el_* names must not appear in the PyTorch named_parameters registry."""
        layer = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=True
        )
        nn_param_names = [name for name, _ in layer.named_parameters()]
        el_nn_params = [n for n in nn_param_names if n.startswith("el_")]
        assert el_nn_params == [], f"el_* params found as nn.Parameters: {el_nn_params}"


class TestEntangledState:
    def test_randomized_entangling_affects_output(self):
        """Two layers sharing identical trainable (theta) params but different
        random entangling params must produce different quantum states, proving
        the randomized entangling layer is active and creates a distinct entangled state.
        """
        layer_a = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=True
        )
        layer_b = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=True
        )

        # Align the trainable rotation params so outputs differ only due to el_*
        _copy_trainable_params(layer_a, layer_b)

        out_a = layer_a()
        out_b = layer_b()

        assert not torch.allclose(
            out_a, out_b, atol=1e-6
        ), "Two layers with different random entangling params produced identical outputs"

    def test_nonrandomized_layers_produce_same_output(self):
        """Two default layers with the same trainable params must produce
        identical outputs (verifying determinism of the non-randomized path)."""
        layer_a = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=False
        )
        layer_b = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=False
        )

        _copy_trainable_params(layer_a, layer_b)

        out_a = layer_a()
        out_b = layer_b()

        assert torch.allclose(
            out_a, out_b, atol=1e-6
        ), "Two non-randomized layers with identical params produced different outputs"

    def test_randomized_output_differs_from_nonrandomized(self):
        """A randomized layer should produce a different quantum state than a
        non-randomized one when given the same trainable params, confirming the
        entangling layer changes the encoded state."""
        layer_default = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=False
        )
        layer_random = angle_encoding_layer(
            num_features=NUM_FEATURES, randomize_entangling=True
        )

        _copy_trainable_params(layer_default, layer_random)

        out_default = layer_default()
        out_random = layer_random()

        assert not torch.allclose(
            out_default, out_random, atol=1e-6
        ), "Randomized layer produces same output as default — entangling params have no effect"
